//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Assets and files from the Resources folder, sorted by uncompressed size:
        /// 2.1 mb  3.4% file1
        /// 2.1 mb  3.4% file2
        ///Used Assets and files from the Resources folder, sorted by uncompressed size:
        /// 2.1 mb  3.4% file3
        /// 2.1 mb  3.4% file4
        ///Used Assets and files from the Resources folder, sorted by uncompressed size:
        /// 2.1 mb  3.4% file5
        /// 2.1 mb  3.4% file6.
        /// </summary>
        internal static string LogWithMultipleBlocksOfFiles {
            get {
                return ResourceManager.GetString("LogWithMultipleBlocksOfFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textures      33.1 mb    54.1% 
        ///Meshes        0.0 kb     0.0% 
        ///Animations    0.0 kb     0.0% 
        ///Sounds        8.3 mb     13.6% 
        ///Shaders       172.8 kb   0.3% 
        ///Other Assets  8.2 mb     13.4% 
        ///Levels        82.1 kb    0.1% 
        ///Scripts       4.7 mb     7.7% 
        ///Included DLLs 6.4 mb     10.5% 
        ///File headers  201.5 kb   0.3% 
        ///Complete size 61.3 mb    100.0% 
        ///
        /// 2.1 mb  3.4% Assets/Spritesheets/v2/Spritesheet1.png
        /// 2.1 mb  3.4% Assets/Spritesheets/v2/Spritesheet2.png
        /// 2.0 mb  3.3% Assets/Spritesheets/v2/Sprit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LogWithoutStartWord {
            get {
                return ResourceManager.GetString("LogWithoutStartWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Assets and files from the Resources folder, sorted by uncompressed size:
        /// 2.1 mb  3.4% file1
        /// 2.1 mb  3.4% file2.
        /// </summary>
        internal static string LogWithSingleBlockOfFiles {
            get {
                return ResourceManager.GetString("LogWithSingleBlockOfFiles", resourceCulture);
            }
        }
    }
}
